# Razvan Dobasu, 23363473 - Operating Systems Project 1
# CSC1021/customshell

shell: src/shell.c
	gcc src/shell.c -o bin/customshell
	@echo "Build complete, run ./bin/customshell"


clean:
	rm -f bin/customshell
	@echo "Cleaned compiled files"


run: shell
	./bin/customshell
